FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_COMPANY_NAME
ARG VITE_PAGE_TITLE
ARG VITE_PAGE_DESCRIPTION
ARG VITE_LOGO_URL
ARG VITE_FAVICON_URL
ARG VITE_TEMPLATE_VARIANT
ARG VITE_SUPPORT_PHONE
ARG VITE_SUPPORT_EMAIL
ARG VITE_SUPPORT_WHATSAPP
ARG VITE_PLAN_PRICE_MONTHLY
ARG VITE_PLAN_PRICE_ANNUAL
ARG VITE_STRIPE_PRICE_ID_ANNUAL
ARG VITE_STRIPE_PRICE_ID_MONTHLY
ARG VITE_PLAN_FEATURES_MONTHLY
ARG VITE_PLAN_FEATURES_ANNUAL
ARG VITE_APP_URL
ARG VITE_WHATSAPP_PREVIEW_URL
ARG VITE_LOGO_WIDTH
ARG VITE_LOGO_HEIGHT
ARG VITE_FAVICON_SIZE
ARG VITE_WHATSAPP_PREVIEW_WIDTH
ARG VITE_WHATSAPP_PREVIEW_HEIGHT

ENV VITE_COMPANY_NAME=$VITE_COMPANY_NAME
ENV VITE_PAGE_TITLE=$VITE_PAGE_TITLE
ENV VITE_PAGE_DESCRIPTION=$VITE_PAGE_DESCRIPTION
ENV VITE_LOGO_URL=$VITE_LOGO_URL
ENV VITE_FAVICON_URL=$VITE_FAVICON_URL
ENV VITE_TEMPLATE_VARIANT=$VITE_TEMPLATE_VARIANT
ENV VITE_SUPPORT_PHONE=$VITE_SUPPORT_PHONE
ENV VITE_SUPPORT_EMAIL=$VITE_SUPPORT_EMAIL
ENV VITE_SUPPORT_WHATSAPP=$VITE_SUPPORT_WHATSAPP
ENV VITE_PLAN_PRICE_MONTHLY=$VITE_PLAN_PRICE_MONTHLY
ENV VITE_PLAN_PRICE_ANNUAL=$VITE_PLAN_PRICE_ANNUAL
ENV VITE_STRIPE_PRICE_ID_ANNUAL=$VITE_STRIPE_PRICE_ID_ANNUAL
ENV VITE_STRIPE_PRICE_ID_MONTHLY=$VITE_STRIPE_PRICE_ID_MONTHLY
ENV VITE_PLAN_FEATURES_MONTHLY=$VITE_PLAN_FEATURES_MONTHLY
ENV VITE_PLAN_FEATURES_ANNUAL=$VITE_PLAN_FEATURES_ANNUAL
ENV VITE_APP_URL=$VITE_APP_URL
ENV VITE_WHATSAPP_PREVIEW_URL=$VITE_WHATSAPP_PREVIEW_URL
ENV VITE_LOGO_WIDTH=$VITE_LOGO_WIDTH
ENV VITE_LOGO_HEIGHT=$VITE_LOGO_HEIGHT
ENV VITE_FAVICON_SIZE=$VITE_FAVICON_SIZE
ENV VITE_WHATSAPP_PREVIEW_WIDTH=$VITE_WHATSAPP_PREVIEW_WIDTH
ENV VITE_WHATSAPP_PREVIEW_HEIGHT=$VITE_WHATSAPP_PREVIEW_HEIGHT

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
